### ISSUE TITLE
T connections arent handled the same like PiNs

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#123]
i think the T connections should be safed at moving using the stretch enabled. but in the moment Ts are broken. would it be possible to handle the Ts like the PiNs?

![sel edge](https://github.com/StefanSchippers/xschem/assets/120017377/4431ca66-0900-48bd-ab23-3a38837fc0ef)
![move edge](https://github.com/StefanSchippers/xschem/assets/120017377/01df7b82-35f5-452d-a854-3ad1d80620f5)
![sel t](https://github.com/StefanSchippers/xschem/assets/120017377/7da2f7ed-1dcb-4867-887f-5639371465ff)
![move t](https://github.com/StefanSchippers/xschem/assets/120017377/8bad568e-d409-42ba-966e-2ac5c2f921b4)

**Comment by StefanSchippers** [comment]
See this short clip.

https://github.com/StefanSchippers/xschem/assets/69359491/47b62c42-6dc5-46cd-8c80-58c1b9b387b3


There is also another move command, in addition to stretch mode move, Shift-M, this will add wire segments to selected instance pins and wire endpoints, instead of stretching existing attached wires. You might want to test this one as well.

See the difference below

![1](https://github.com/StefanSchippers/xschem/assets/69359491/033ec98d-4389-4ced-92bc-e2065911c671) 

![2](https://github.com/StefanSchippers/xschem/assets/69359491/4dbd9d9c-15e3-438c-9f48-3008098d2a8c)

**Comment by olisnr** [comment]
great, i only need to "set autotrim_wires 1" in xschemrc. 

thanks!
