### ISSUE TITLE
Extended draw shapes capabilities

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#177]
Hello!
It would be great to see the ability to draw more complex shapes - ellipse, Bézier curve, etc.
These shapes will greatly simplify component symbols creation, currently I can only approximate it with segmented line.
Also would be great to add scaling ability for already placed shapes.

Thank you in advance, George.

**Comment by StefanSchippers** [comment]
I have added a first implementation of bezier curves. 
They are essentially a variation built on top of the polygon shape.
Draw a multipoint polygon (key=`p`) (npoints >= 3) , set attribute **bezier=1** on this shape, it will transform into a 
composite quadratic bezier spline. I have done tests with quadratic and cubic bezier splines. 
Quadratic beziers seem more useful, since they can be bent more easily than higher order polynomial curves.
I have to improve the UI for selecting and more easily moving the control points, but it is already useable. 
You can also transform a closed polygon into a bezier and in this case it can be filled (by adding attribute **fill=1**).

Attached the example schematic. Please do a test.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/e797b03a-db45-4675-922d-a935c5a7b98b)
[test_bezier.zip](https://github.com/StefanSchippers/xschem/files/14442224/test_bezier.zip)

**Comment by georgtree** [comment]
Wow, that was really fast, I tested it and all works great, thank you! 
I will play with it a little bit more!

**Comment by StefanSchippers** [comment]
Thank you for testing.
I was a bit scared by the math, but turned out to be simpler than I thought.

For the ellips I will look at it. One important question is if you need X/Y oriented ellipses or any angle.

In the mean time I se beziers approximate ellipses quite well. Just start at the correct point as shown.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/8c8cb31a-baf5-4a72-898e-11ef9a66cdf4)

**Comment by georgtree** [comment]
Hello, I need XY only for drawing pretty-looking symbols

**Comment by StefanSchippers** [comment]
I have improved a bit the bezier editing. If you select one you can click and drag directly the control points. This applies also for normal polygons. Please test. Thanks!

Last thing I need to improve a bit is selection. Now selecting a bezier works well if you click one of the endpoints or close to a control point. I need to let user select the curve also by clicking any location close to the bezier line. 

![1](https://github.com/StefanSchippers/xschem/assets/69359491/3be2ba0a-d008-4154-a0e9-0542d0f184e2)

**Comment by georgtree** [comment]
Hello, thank you, it is very convenient and works as expected!

**Comment by georgtree** [comment]
Hello!
Sorry for asking, but do you have any thoughts about the time the ellipsis will be available to draw? I am not pushing you just ask because I have a lot of symbols to modify and want to understand if it is worth to wait for proper ellipsis implementation instead of bezier approximation...
Thank you in advance!

**Comment by georgtree** [comment]
Hello, all works great, thank you!
![image](https://github.com/StefanSchippers/xschem/assets/113975847/41d73a70-9b71-430c-b881-1f583e8457d8)

**Comment by georgtree** [comment]
Hello, find the issue - when component is flipped or rotated, I get this behaviour:
![image](https://github.com/StefanSchippers/xschem/assets/113975847/32ad6c89-b83f-4602-a3ac-da1913e7b4da)
![image](https://github.com/StefanSchippers/xschem/assets/113975847/9d5ec0fb-3331-441a-9a18-502920d6b762)
Looks like the issue is in absolute definition of angles...

**Comment by StefanSchippers** [comment]
Yes this will be fixed soon. Thanks

**Comment by georgtree** [comment]
Hello, I tried with last commit, it works with ellipse that I place onto schematic, but if I generate symbol from tcl script, the problem is the same.

**Comment by StefanSchippers** [comment]
Yes, bare ellipses are fixed now. Next commit will address symbols with
ellipses.

Il Sab 6 Apr 2024, 17:25 georgtree ***@***.***> ha scritto:

**Comment by StefanSchippers** [comment]
Last commit hopefully does correct transformations for ellipses inside symbols. Please test.
Thank you for the feedback.

**Comment by georgtree** [comment]
Hello!
Just tested, all works fine, thank you :)
