### ISSUE TITLE
tcleval() question

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#225]
Hello!
I tried to use tcleval(), and for text on schematic it works only if I add name into the props like this:
![image](https://github.com/user-attachments/assets/aa3b242c-9d17-4ce4-bd9e-1dbb5ad3998b)
If I remove it, I get:
![image](https://github.com/user-attachments/assets/1c569f46-7b5c-40da-91a5-34bbcd4aac1b)

The issue here is that I want to use tcl substitution for text of the symbol, that is shown only if particular variables is set.
Thank you in advance, George.

**Comment by StefanSchippers** [comment]
to enable the tcl substitution either use `name=inst_name` so you can also use the `@var` variables related to the specified instance (like `@symname`, `@name`, `@symref`, `@#PLUS:spice_get_voltage`) or If you just need tcl evaluation put attribute `floater=1` in the props textbox.

The reason is to avoid doing tcl substitutions on all texts since this step is slower.

**Comment by georgtree** [comment]
I got it, thank you!
