### ISSUE TITLE
Request to support to import Viewdraw schematic

### ISSUE THREAD

**Issue by lehaianh1986** [StefanSchippers/xschem#39]
Hi Stefan,

Can you support to import Viewdraw schematic into xschem? I saw some converter can be modified to reuse such as https://github.com/ljmljz/schematic-file-converter

**Comment by StefanSchippers** [comment]
Hi, creating a converter can be done. The difficult part is to get the specification of the file format.
I will look into above link and follow up here.
Thank you

**Comment by lehaianh1986** [comment]
Hi Stefan,

I have this document https://drive.google.com/file/d/1URzoXz9L92Im5TuJ1_kPXkHP786zV3_x/view?usp=sharing

**Comment by lehaianh1986** [comment]
Hi Stefan,

If you need some Viewdraw file to test, I can send it. Please pm to my gmail lehaianh1986

**Comment by StefanSchippers** [comment]
I have started to parse the viewdraw example files, i am starting with the symbols. So far it seems that the translated symbols are slightly different from the images (different text positions, different aspect ratio), and since there is a 1:1 mapping between the viewdraw files and the translated xschem files, are you sure the NMOS.1 and PMOS.1 files you sent me are exactly the ones referring to the images in pictures?

Here is the PMOS.1 converted to xschem PMOS.sym (top is image, bottom is xschem) Some details are yet to be implemented, like the circle color, but these are details, i am concerned about the size for now:

![1](https://user-images.githubusercontent.com/69359491/148983694-70f0cacb-b5ce-4292-9128-63d6279ba13b.png)

and here the NMOS.1:

![2](https://user-images.githubusercontent.com/69359491/148983786-e78e610f-ed8c-43f0-b5c4-b1a24fb609a5.png)

In your pictures the W=... and L=.. texts are in the same positions in PMOS and NMOS, while the NMOS.1 and PMOS.1 viewdraw files have different coordinates and thus xschem PMOS.sym and NMOS.sym show these texts in different positions.

**Comment by StefanSchippers** [comment]
I have some progress in the import process. The following is what i get so far for the dti_28hc_6p5t_40_nand2x1.1 nand schematic:

![1](https://user-images.githubusercontent.com/69359491/149045454-38f4d9d5-ff21-43af-af13-177747544fd8.png)

However this schematic includes a symbol called **NM.1** for the nmos transistor and **PM.1** for the pmos transistor.
The test case i got from you has **NMOS.1** and **PMOS.1**, and as shown they are of different size. I have put the two transistors manually in the xschem schematic to show they don't fit into the rest of the schematic.

Can you please send me the **NM.1** and **PM.1** files?

Thanks

**Comment by StefanSchippers** [comment]
I have verified that the flip flop, dti_28hc_6p5t_40_ffqx1.1, uses the PMOS.1 and NMOS.1 symbols so i am able to generate a valid schematic. If you have a picture of this schematic that would be great so i can adjust labels and all the remaining details.
![2](https://user-images.githubusercontent.com/69359491/149048654-70c9a493-d725-4f87-a5b9-332d29a0571e.png)
