### ISSUE TITLE
bus=true does not render in symbol lines

### ISSUE THREAD

**Issue by AhmedLilah** [StefanSchippers/xschem#53]
while making my own symbols I used the bus=true on some of the lines it works fine on windows
![TestSchematicWithPins](https://user-images.githubusercontent.com/67424460/162564404-1a7f9f1e-0456-4a93-ad7f-15810c72ca4b.png)

but in Linux (wsl2 Debian) the line is not rendered at the 3x width in either the symbols file or in the schematic file 
![TestSchematicWithPinsLinux](https://user-images.githubusercontent.com/67424460/162564398-9ab3b29b-4cab-49af-ae9e-0caa512824af.png)

**Comment by StefanSchippers** [comment]
can you please open a new schematic in linux, draw 2 lines and set bus=true
attribute on one of these, do they look different?

Il Sab 9 Apr 2022, 10:54 Ahmed S. Lilah ***@***.***> ha
scritto:

**Comment by AhmedLilah** [comment]
> aking my own symbols I used the bus=true on som

the top line have is a bus

![image](https://user-images.githubusercontent.com/67424460/162568788-fde3b9be-fafa-4df8-acc2-9f1366a3737f.png)

**Comment by AhmedLilah** [comment]
also the line width does not work on windows and in both OS the lines do get a lot thinner without any mods while zoning and redraw doesn't return them back have to close the program and open it again

**Comment by StefanSchippers** [comment]
Did you install xschem from source files ? because packaged xschem versions in ubuntu/debian are too old. 
If i draw 2 lines and set bus=true on one of them this is what i get:
![1](https://user-images.githubusercontent.com/69359491/162607000-005257ae-6214-41e1-8765-7c602162b9fe.png)
Ensure menu option View->Toggle variable line width is selected.
If you zoom out a lot of course the lines will get 1 pixel thin and you won't see any difference. This is intended behavior.
