### ISSUE TITLE
The plots appending [mag]

### ISSUE THREAD

**Issue by rafmag** [StefanSchippers/xschem#67]
I was making the changes to the AC plots and noticed that it would append [mag] see below. Is there any way to remove this or change the unit?

![image](https://user-images.githubusercontent.com/14288365/183093204-0d24de09-8a77-4cdd-af6e-66e2b295cd9c.png)

**Comment by StefanSchippers** [comment]
I have made the fix. Do a `git pull && make install`. The 'Mag' string was previously 'dB' to inform user xschem was storing the value in dB. Since we have now made it more general (just store magnitude and phase) i replaced 'dB' with 'Mag(nitude)', however I agree with you. Since you can define your own alias name there is no need to clutter the wave labels with that info.
Please test and close if all ok

**Comment by StefanSchippers** [comment]
PS:  As you probably see the X log axis is now a user option (not implied by AC analysis as before) . There is also a Y log option, the button is there but still not implemented.

**Comment by rafmag** [comment]
clean! It's working.
