### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by realsurgent** [StefanSchippers/xschem#92]
When I run "make -j4" I get the following error and can't install xschem.  
![image](https://user-images.githubusercontent.com/56458329/198829588-f6a17cf0-e8bd-458f-83de-ef0b5c133d36.png)

**Comment by StefanSchippers** [comment]
You probably ran ./configure --prefix=/home/schippes.
You must use your username.

Il Sab 29 Ott 2022, 13:45 Denizhan ***@***.***> ha scritto:

**Comment by realsurgent** [comment]
I did what you suggested but it didn't work. But I did run setup from ` sudo apt-get install xschem`.

**Comment by StefanSchippers** [comment]
Do not install xschem from the ubuntu app store with apt-get. the packaged xschem that comes with Ubuntu/Debian/Fedora is too old.

remove the xschem package: `sudo apt-get purge xschem`
Install xschem by  cloning the sources, follow the manual [here](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).

**Comment by realsurgent** [comment]
> Do not install xschem from the ubuntu app store with apt-get. the packaged xschem that comes with Ubuntu/Debian/Fedora is too old.
> 
> remove the xschem package: `sudo apt-get purge xschem` Install xschem by cloning the sources, follow the manual [here](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).

I did your suggestion and I still get the same error. Also xschem I downloaded from the app store works as I want.

**Comment by StefanSchippers** [comment]
please post the steps you did from git clone to make install. Also attach the xschem_git/src/scconfig/config.log
xschem from ubuntu appstore is too old and you will get in trouble sooner or later.

remove the packaged xschem with sudo apt-get purge xschem, remove the source xschem directory, follow every step in the [manual](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).

It is impossible that make install tries to install in /home/schippes since you are on a different username, unless you typed schippes somewhere.

**Comment by realsurgent** [comment]
I did it. All I had to write was `sudo make install`
